"""Interal reference data for email cleanup
   
   The below code was adapted from maxmind's minfraud python client.
   
   https://github.com/maxmind/minfraud-api-python
   Details of the clean/normalization process ar described here:
   https://dev.maxmind.com/minfraud/normalizing-email-addresses-for-minfraud
"""


_TYPO_DOMAINS = {
    # gmail.com
    "gmai.com": "gmail.com",
    "gamil.com": "gmail.com",
    "gmali.com": "gmail.com",
    "gmial.com": "gmail.com",
    "gmil.com": "gmail.com",
    "gmaill.com": "gmail.com",
    "gmailm.com": "gmail.com",
    "gmailo.com": "gmail.com",
    "gmailyhoo.com": "gmail.com",
    "yahoogmail.com": "gmail.com",
    # outlook.com
    "putlook.com": "outlook.com",
}

_TYPO_TLDS = {
    "comm": "com",
    "commm": "com",
    "commmm": "com",
    "comn": "com",
    "cbm": "com",
    "ccm": "com",
    "cdm": "com",
    "cem": "com",
    "cfm": "com",
    "cgm": "com",
    "chm": "com",
    "cim": "com",
    "cjm": "com",
    "ckm": "com",
    "clm": "com",
    "cmm": "com",
    "cnm": "com",
    "cpm": "com",
    "cqm": "com",
    "crm": "com",
    "csm": "com",
    "ctm": "com",
    "cum": "com",
    "cvm": "com",
    "cwm": "com",
    "cxm": "com",
    "cym": "com",
    "czm": "com",
    "col": "com",
    "con": "com",
    "dom": "com",
    "don": "com",
    "som": "com",
    "son": "com",
    "vom": "com",
    "von": "com",
    "xom": "com",
    "xon": "com",
    "clam": "com",
    "colm": "com",
    "comcom": "com",
}

_EQUIVALENT_DOMAINS = {
    "googlemail.com": "gmail.com",
    "pm.me": "protonmail.com",
    "proton.me": "protonmail.com",
    "yandex.by": "yandex.ru",
    "yandex.com": "yandex.ru",
    "yandex.kz": "yandex.ru",
    "yandex.ua": "yandex.ru",
    "ya.ru": "yandex.ru",
}

_FASTMAIL_DOMAINS = {
    "123mail.org",
    "150mail.com",
    "150ml.com",
    "16mail.com",
    "2-mail.com",
    "4email.net",
    "50mail.com",
    "airpost.net",
    "allmail.net",
    "bestmail.us",
    "cluemail.com",
    "elitemail.org",
    "emailcorner.net",
    "emailengine.net",
    "emailengine.org",
    "emailgroups.net",
    "emailplus.org",
    "emailuser.net",
    "eml.cc",
    "f-m.fm",
    "fast-email.com",
    "fast-mail.org",
    "fastem.com",
    "fastemail.us",
    "fastemailer.com",
    "fastest.cc",
    "fastimap.com",
    "fastmail.cn",
    "fastmail.co.uk",
    "fastmail.com",
    "fastmail.com.au",
    "fastmail.de",
    "fastmail.es",
    "fastmail.fm",
    "fastmail.fr",
    "fastmail.im",
    "fastmail.in",
    "fastmail.jp",
    "fastmail.mx",
    "fastmail.net",
    "fastmail.nl",
    "fastmail.org",
    "fastmail.se",
    "fastmail.to",
    "fastmail.tw",
    "fastmail.uk",
    "fastmail.us",
    "fastmailbox.net",
    "fastmessaging.com",
    "fea.st",
    "fmail.co.uk",
    "fmailbox.com",
    "fmgirl.com",
    "fmguy.com",
    "ftml.net",
    "h-mail.us",
    "hailmail.net",
    "imap-mail.com",
    "imap.cc",
    "imapmail.org",
    "inoutbox.com",
    "internet-e-mail.com",
    "internet-mail.org",
    "internetemails.net",
    "internetmailing.net",
    "jetemail.net",
    "justemail.net",
    "letterboxes.org",
    "mail-central.com",
    "mail-page.com",
    "mailandftp.com",
    "mailas.com",
    "mailbolt.com",
    "mailc.net",
    "mailcan.com",
    "mailforce.net",
    "mailftp.com",
    "mailhaven.com",
    "mailingaddress.org",
    "mailite.com",
    "mailmight.com",
    "mailnew.com",
    "mailsent.net",
    "mailservice.ms",
    "mailup.net",
    "mailworks.org",
    "ml1.net",
    "mm.st",
    "myfastmail.com",
    "mymacmail.com",
    "nospammail.net",
    "ownmail.net",
    "petml.com",
    "postinbox.com",
    "postpro.net",
    "proinbox.com",
    "promessage.com",
    "realemail.net",
    "reallyfast.biz",
    "reallyfast.info",
    "rushpost.com",
    "sent.as",
    "sent.at",
    "sent.com",
    "speedpost.net",
    "speedymail.org",
    "ssl-mail.com",
    "swift-mail.com",
    "the-fastest.net",
    "the-quickest.com",
    "theinternetemail.com",
    "veryfast.biz",
    "veryspeedy.net",
    "warpmail.net",
    "xsmail.com",
    "yepmail.net",
    "your-mail.com",
}

_YAHOO_DOMAINS = {
    "y7mail.com",
    "yahoo.at",
    "yahoo.be",
    "yahoo.bg",
    "yahoo.ca",
    "yahoo.cl",
    "yahoo.co.id",
    "yahoo.co.il",
    "yahoo.co.in",
    "yahoo.co.kr",
    "yahoo.co.nz",
    "yahoo.co.th",
    "yahoo.co.uk",
    "yahoo.co.za",
    "yahoo.com",
    "yahoo.com.ar",
    "yahoo.com.au",
    "yahoo.com.br",
    "yahoo.com.co",
    "yahoo.com.hk",
    "yahoo.com.hr",
    "yahoo.com.mx",
    "yahoo.com.my",
    "yahoo.com.pe",
    "yahoo.com.ph",
    "yahoo.com.sg",
    "yahoo.com.tr",
    "yahoo.com.tw",
    "yahoo.com.ua",
    "yahoo.com.ve",
    "yahoo.com.vn",
    "yahoo.cz",
    "yahoo.de",
    "yahoo.dk",
    "yahoo.ee",
    "yahoo.es",
    "yahoo.fi",
    "yahoo.fr",
    "yahoo.gr",
    "yahoo.hu",
    "yahoo.ie",
    "yahoo.in",
    "yahoo.it",
    "yahoo.lt",
    "yahoo.lv",
    "yahoo.nl",
    "yahoo.no",
    "yahoo.pl",
    "yahoo.pt",
    "yahoo.ro",
    "yahoo.se",
    "yahoo.sk",
    "ymail.com",
}
